Repository PlaNet-Devteam/sns-project-client, pull requests merged in 2023-08, with the labels that each got.

#28 refactor: 무한스크롤 커스텀 훅 생성하기
  next.config.js
  src/components/nav/bottomNav/BottomNav.tsx
  src/components/profile/ProfileFeedList.tsx
  src/hooks/.gitkeep
  src/hooks/useInfinityScroll.ts
  src/hooks/useIsScrolling.ts
  src/pages/[username]/feed/index.tsx
  src/pages/feed/index.tsx
Labels: refactor

#31 Feat/feed carousel
  src/components/common/Modal.tsx
  src/components/feed/FeedImgModal.tsx
  src/components/feed/FeedItem.tsx
  src/components/profile/ProfileFeedListItem.tsx
  src/styles/components/feed/_feed-modal.scss
  src/styles/components/feed/_index.scss
Labels: feat

#39 fix: user별 피드 목록 api 경로 수정
  src/services/feed/index.ts
Labels: fix

#38 refactor: 피드 삭제후 목록 쿼리 불러오기
  src/components/feed/FeedItem.tsx
Labels: refactor
