Repository PlaNet-Devteam/sns-project-client, pull requests merged in 2023-09, with the labels that each got.

#41 refactor: 유저별 피드 목록 및 아이템 / 프로필 페이지 리팩토링
  src/components/feed/FeedItem.tsx
  src/components/layouts/ProfileLayout.tsx
  src/components/nav/bottomNav/BottomNav.tsx
  src/pages/[username]/edit/index.tsx
  src/services/user/index.ts
Labels: refactor

#49 feat: 피드 모달 변경, 동작 이슈 해결하기
  src/components/common/FeedModal.tsx
  src/components/feed/Carousel.tsx
  src/components/feed/FeedImg.tsx
  src/components/feed/FeedImgModal.tsx
  src/components/feed/FeedItem.tsx
  src/components/profile/ProfileFeedListItem.tsx
  src/core/types/feed/feed-image.interface.ts
  src/store/feedAtom.ts
  src/styles/components/common/_modal.scss
Labels: feat, refactor

#46 feat: USER 프로필 이미지 업로드 추가 및 useInfinityScroll 훅 리팩토링
  src/components/common/Button.tsx
  src/components/common/LoadingLayer.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/feed/FeedItem.tsx
  src/components/layouts/ProfileLayout.tsx
  src/components/profile/ProfileFeedList.tsx
  src/components/profile/ProfileImage.tsx
  src/components/profile/ProfileInfo.tsx
  src/core/types/error/axios-error-response.type.ts
  src/core/types/error/index.ts
  src/core/types/index.ts
  src/core/types/user/user-update.interface.ts
  src/hooks/useInfinityScroll.ts
  src/pages/[username]/edit/index.tsx
  src/pages/feed/create/index.tsx
  src/pages/feed/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/styles/components/common/_button.scss
  src/styles/components/common/_index.scss
  src/styles/components/common/_loading-layer.scss
  src/styles/components/common/_loading-spinner.scss
  src/styles/components/feed/_index.scss
  src/styles/components/profile/_profile-info.scss
  src/utils/uploadImage.ts
Labels: feat

#55 fix: localstorage 에러 수정, useLayoutEffect 공유사항
  src/hooks/useLocalStorage.ts
Labels: fix

#59 feat: feed 수정기능 구현
  src/components/feed/FeedItem.tsx
  src/core/types/feed/feed-image.interface.ts
  src/core/types/feed/feed-modify.interface.ts
  src/pages/feed/modify/index.tsx
  src/services/feed/index.ts
  src/store/feedAtom.ts
Labels: feat

#62 docs: README.md 수정
  README.md
Labels: docs

#65 feat: 코멘트 CRUD 기능 추가
  src/components/comment/Comment.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentInputModal.module.scss
  src/components/comment/CommentInputModal.tsx
  src/components/comment/CommentItem.tsx
  src/components/comment/Header.tsx
  src/components/comment/Input.tsx
  src/components/feed/FeedItem.tsx
  src/components/profile/ProfileFeedList.tsx
  src/core/enum/common/index.ts
  src/core/enum/common/order-by.enum.ts
  src/core/types/comment/comment-create.interface.ts
  src/core/types/comment/comment-list.interface.ts
  src/core/types/comment/comment-update.interface.ts
  src/core/types/comment/comment.interface.ts
  src/core/types/comment/index.ts
  src/core/types/common/base-list.interface.ts
  src/core/types/common/base-props.interface.ts
  src/core/types/common/index.ts
  src/core/types/feed/feed-list.interface.ts
  src/hooks/useInfinityScroll.ts
  src/pages/[username]/feed/index.tsx
  src/pages/comment/[feedId].tsx
  src/pages/feed/[id]/comment/index.tsx
  src/pages/feed/index.tsx
  src/services/comment/index.ts
  src/store/commentAtom.ts
  src/styles/components/comment/_comment.scss
  src/styles/components/comment/_index.scss
  src/styles/components/comment/_input.scss
Labels: feat

#66 feat: 피드 좋아요 기능 추가
  src/components/feed/FeedItem.tsx
  src/core/types/feed/feed-list.interface.ts
  src/core/types/feed/feed.interface.ts
  src/pages/feed/index.tsx
  src/services/feed/index.ts
Labels: feat

#68 refactor: useState 리팩토링
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentItem.tsx
  src/components/feed/FeedItem.tsx
  src/components/layouts/BaseLayout.tsx
  src/components/layouts/ProfileLayout.tsx
  src/components/profile/ProfileFeedTabs.tsx
  src/core/types/feed/feed-list.interface.ts
  src/store/feedAtom.ts
  src/store/profileAtom.ts
  src/styles/components/comment/_comment.scss
  src/styles/components/comment/_input.scss
Labels: fix, refactor
