Repository PlaNet-Devteam/sns-project-client, pull requests merged in 2024-03, with the labels that each got.

#105 docs: next.config.js 수정
  .gitignore
  next.config.js
Labels: feat, docs

#108 docs: rerwrites() 옵션 제거
  next.config.js
Labels: fix, docs

#109 docs: domain 주소 추가
  next.config.js
Labels: feat

#111 docs: 불필요 설정 제거
  next.config.js
Labels: docs

#112 refactor: socket SocektProvider 및 useSocket 커스텀 훅 추가
  package.json
  src/components/direct-message/DirectMessageList.module.scss
  src/components/direct-message/DirectMessageList.tsx
  src/components/direct-message/DirectMessageUserListItem.tsx
  src/contexts/SocketContext.tsx
  src/hooks/index.ts
  src/hooks/useSocket.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/direct/inbox/index.tsx
  src/pages/direct/new/index.tsx
  src/pages/index.tsx
  yarn.lock
Labels: refactor

#113 fix: Head 태그 수정
  src/pages/_document.tsx
Labels: fix

#115 test: 소켓 테스트 주석
  src/components/direct-message/DirectMessageList.tsx
  src/components/direct-message/DirectMessageUserListItem.tsx
  src/pages/_app.tsx
  src/pages/direct/inbox/index.tsx
  src/pages/direct/new/index.tsx
  src/styles/components/nav/_bottom_nav.scss
Labels: refactor

#117 style: global font css 추가
  src/styles/globals.scss
Labels: style

#118 dev branch main 병합
  src/styles/globals.scss
Labels: style

#119 docs: udpate RAEDME.md
  README.md
Labels: docs

#120 docs: udpate RAEDME.md
  README.md
Labels: docs

#123 캐러셀 동작 방식 변경
  package-lock.json
  package.json
  src/components/feed/Carousel.module.scss
  src/components/feed/Carousel.tsx
  src/hooks/useCarouselSize.ts
  src/utils/dragEvent.ts
  yarn.lock
Labels: fix, refactor

#124 feat: 피드 상세 및 공유하기 버튼 추가
  src/components/common/form/InputField.tsx
  src/components/dialog/Dialog.tsx
  src/components/dialog/DialogHeader.module.scss
  src/components/dialog/DialogHeader.tsx
  src/components/explore/ExploreTagInfo.tsx
  src/components/feed/FeedItem.tsx
  src/components/feed/FeedItemActionButtons.tsx
  src/components/feed/FeedItemCountInfo.tsx
  src/components/feed/FeedShareModal.tsx
  src/components/layouts/BaseLayout.tsx
  src/components/layouts/ProfileLayout.tsx
  src/components/metatag/MetaTag.tsx
  src/components/nav/topHeader/TopHeader.tsx
  src/components/profile/ProfileFeedModal.tsx
  src/core/base.service.ts
  src/hooks/index.ts
  src/hooks/useAuth.ts
  src/hooks/useIsMobile.ts
  src/pages/_app.tsx
  src/pages/explore/feed/tags/[tagName]/index.tsx
  src/pages/feed/[id]/index.tsx
  src/services/feed/index.ts
  src/store/feedAtom.ts
Labels: feat, refactor

#125 style: carousel 스타일 수정
  src/components/common/FeedModal.module.scss
  src/components/feed/Carousel.module.scss
Labels: style

#126 refactor: update carousel logic
  package-lock.json
  package.json
  src/components/common/FeedModal.module.scss
  src/components/feed/Carousel.module.scss
  src/components/feed/Carousel.tsx
  src/hooks/useCarouselSize.ts
  src/utils/dragEvent.ts
  yarn.lock
Labels: refactor

#127 fix: url 경로 수정 및 회원가입 구글로그인 버튼 연동
  README.md
  src/components/common/form/InputField.tsx
  src/components/dialog/Dialog.tsx
  src/components/dialog/DialogHeader.module.scss
  src/components/dialog/DialogHeader.tsx
  src/components/explore/ExploreTagInfo.tsx
  src/components/feed/FeedItem.tsx
  src/components/feed/FeedItemActionButtons.tsx
  src/components/feed/FeedItemCountInfo.tsx
  src/components/feed/FeedShareModal.tsx
  src/components/layouts/BaseLayout.tsx
  src/components/layouts/ProfileLayout.tsx
  src/components/metatag/MetaTag.tsx
  src/components/nav/topHeader/TopHeader.tsx
  src/components/profile/ProfileFeedModal.tsx
  src/core/base.service.ts
  src/hooks/index.ts
  src/hooks/useAuth.ts
  src/hooks/useIsMobile.ts
  src/pages/_app.tsx
  src/pages/explore/feed/tags/[tagName]/index.tsx
  src/pages/feed/[id]/index.tsx
  src/pages/signup/index.tsx
  src/services/feed/index.ts
  src/store/feedAtom.ts
Labels: fix

#128 fix: url 경로 수정 및 회원가입 구글로그인 버튼 연동
  src/components/common/form/InputField.tsx
  src/components/feed/FeedItemActionButtons.tsx
  src/pages/signup/index.tsx
Labels: fix

#131 fix: 사용자 탐색 버그 수정 및 유저명 링크 추가
  src/components/explore/ExploreUserList.tsx
  src/components/explore/ExploreUserListItem.tsx
Labels: fix

#132 fix: 사용자 탐색 버그 수정 및 유저명 링크 추가
  src/components/explore/ExploreUserList.tsx
  src/components/explore/ExploreUserListItem.tsx
Labels: fix

#135 fix: 피드 Action Button 이벤트시 newFeeds query key 갱신
  src/components/feed/FeedItemActionButtons.tsx
  src/pages/feed/create/index.tsx
  src/pages/message/userlist/index.tsx
  src/utils/uploadImage.ts
Labels: fix, refactor

#136 style: feed 및 feedModal 관련 css 수정
  src/components/common/FeedModal.module.scss
  src/components/feed/Carousel.module.scss
  src/components/feed/Carousel.tsx
  src/components/feed/FeedImg.module.scss
Labels: feat

#137 fix: meta태그 및 navagater.share 텍스트 내용 수정
  src/components/feed/FeedItemActionButtons.tsx
  src/pages/feed/[id]/index.tsx
Labels: fix, refactor

#138 Merge pull request from Dev
  src/components/common/FeedModal.module.scss
  src/components/feed/Carousel.module.scss
  src/components/feed/Carousel.tsx
  src/components/feed/FeedImg.module.scss
  src/components/feed/FeedItemActionButtons.tsx
  src/pages/feed/[id]/index.tsx
  src/pages/feed/create/index.tsx
  src/pages/message/userlist/index.tsx
  src/utils/uploadImage.ts
Labels: fix, refactor

#139 refactor: payload 관련 버그 수정
  src/components/layouts/ProfileLayout.tsx
  src/components/nav/topHeader/TopHeader.tsx
  src/hooks/useAuth.ts
  src/pages/feed/[id]/index.tsx
Labels: refactor

#140 refactor: 이미지 컴포넌트 공통 처리를 위한 리팩토링
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentReplyInput.tsx
  src/components/common/UserProfileImage.tsx
  src/components/common/img/BaseImage.module.scss
  src/components/common/img/BaseImage.tsx
  src/components/common/img/ThumbImage.tsx
  src/components/explore/ExploreTagInfo.tsx
  src/components/feed/Carousel.tsx
  src/components/feed/FeedImg.tsx
  src/components/profile/ProfileFeedListItem.tsx
  src/components/profile/ProfileImage.tsx
  src/pages/feed/modify/index.tsx
  src/pages/message/userlist/index.tsx
  src/styles/components/profile/_profile-info.scss
Labels: refactor

#141 Merge pull request main from dev
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentReplyInput.tsx
  src/components/common/UserProfileImage.tsx
  src/components/common/img/BaseImage.module.scss
  src/components/common/img/BaseImage.tsx
  src/components/common/img/ThumbImage.tsx
  src/components/explore/ExploreTagInfo.tsx
  src/components/feed/Carousel.tsx
  src/components/feed/FeedImg.tsx
  src/components/layouts/ProfileLayout.tsx
  src/components/nav/topHeader/TopHeader.tsx
  src/components/profile/ProfileFeedListItem.tsx
  src/components/profile/ProfileImage.tsx
  src/hooks/useAuth.ts
  src/pages/feed/[id]/index.tsx
  src/pages/feed/modify/index.tsx
  src/pages/message/userlist/index.tsx
  src/styles/components/profile/_profile-info.scss
Labels: refactor
